apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: databases.example.demo.k8s.io
spec:
  group: example.demo.k8s.io
  names:
    kind: Database
    plural: databases
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            encoding:
              enum:
              - unicode
              - uft-8
              - ascii
              type: string
            password:
              maxLength: 20
              minLength: 8
              type: string
            replicas:
              format: int32
              type: integer
            user:
              type: string
          required:
          - user
          - password
          - replicas
          type: object
        status:
          properties:
            availableReplicas:
              format: int32
              type: integer
          required:
          - availableReplicas
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
